name: HTML Check

on: [push]

jobs:
  check-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: HTML Validator
        uses: Cyb3r-Jak3/html5validator-action@v0.6.0
